### ISSUE TITLE
Segfault on empty input

### ISSUE THREAD

**Issue by nanoqsh** [Amchik/tableflip#1]
Thanks for the greatest tool! I deleted Excel from my laptop finally!
I want to generate a report for my boss, this is how many tasks I've done in this quarter.

Use case:
```
nano@npc > touch test
nano@npc > ./tableflip test
Segmentation fault (core dumped)
```

**Comment by er2off** [comment]
To fix this issue, we need 1169 FreeBSD developers :)

**Comment by Amchik** [comment]
Yes, C is so hard.

Try the new version rewritten in rust: [Amchik/tableflip-rust](https://github.com/Amchik/tableflip-rust)

**Comment by er2off** [comment]
> Yes, C is so hard.
> 
> Try the new version rewritten in rust: [Amchik/tableflip-rust](https://github.com/Amchik/tableflip-rust

Rust version is just Hello world without tables and other. So this issue need to be reopened.

**Comment by Amchik** [comment]
> > Yes, C is so hard.
> > Try the new version rewritten in rust: [Amchik/tableflip-rust](https://github.com/Amchik/tableflip-rust
> 
> Rust version is just Hello world without tables and other. So this issue need to be reopened.

Rust version still in progress
